from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def resetwindow(self):
        self.label1.setText("")
        self.label2.setText("")
        self.label3.setText("")
        self.label4.setText("")
        self.label5.setText("")
        self.label6.setText("")
        self.label7.setText("") 
        self.label8.setText("")
        self.label9.setText("") 
        
    def X_user(self):
        self.stackedWidget.setCurrentIndex(1)
    def O_user(self):
        self.stackedWidget.setCurrentIndex(1)
        
    def gamepage(self,uservalue):
        
        printvalue(uservalue)
    def printvalueX(self):
        if (position==1):
            self.label1.setText("X") 
        elif (position==2):
            self.label2.setText("X")                
        elif (position==3):
            self.label3.setText("X")
        elif (position==4):
            self.label4.setText("X")
        elif (position==5):
            self.label5.setText("X")
        elif (position==6):
            self.label6.setText("X")
        elif (position==7):
            self.label7.setText("X")
        elif (position==8):
            self.label8.setText("X")
        else:
            self.label9.setText(uservalue)    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)        
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(210, 480, 321, 51))
        self.outputlabel.setText("")
        self.outputlabel.setObjectName("outputlabel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 20, 651, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.select_X = QtWidgets.QPushButton(self.page_2)       
        self.select_X.setGeometry(QtCore.QRect(240, 260, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.select_X.setFont(font)
        self.select_X.setObjectName("select_X")
        self.select_X.clicked.connect(self.X_user)
        self.select_O = QtWidgets.QPushButton(self.page_2)
        self.select_O.setGeometry(QtCore.QRect(240, 170, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.select_O.setFont(font)
        self.select_O.setObjectName("select_O")
        self.select_O.clicked.connect(self.O_user)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(120, 70, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 391, 407))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label1.setFont(font)
        self.label1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label1.setStyleSheet("background:white;")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label1.clicked.connect(self.printvalue)
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label4.setFont(font)
        self.label4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label4.setStyleSheet("background:white;")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 1, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label3.setFont(font)
        self.label3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label3.setStyleSheet("background:white;")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 2, 1, 1)
        self.label6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label6.setFont(font)
        self.label6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label6.setStyleSheet("background:white;")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 1, 2, 1, 1)
        self.label7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label7.setFont(font)
        self.label7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label7.setStyleSheet("background:white;")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 2, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label2.setFont(font)
        self.label2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label2.setStyleSheet("background:white;")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 1, 1, 1)
        self.label8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label8.setFont(font)
        self.label8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label8.setStyleSheet("background:white;")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 2, 1, 1, 1)
        self.label9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label9.setFont(font)
        self.label9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label9.setStyleSheet("background:white;")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 2, 2, 1, 1)
        self.label5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        self.label5.setFont(font)
        self.label5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label5.setStyleSheet("background:white;")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 220, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 190, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 160, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 130, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 100, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 70, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.page)
        self.pushButton_1.setGeometry(QtCore.QRect(470, 40, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_9 = QtWidgets.QPushButton(self.page)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 280, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 250, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.reset = QtWidgets.QPushButton(self.page)
        self.reset.setGeometry(QtCore.QRect(450, 410, 141, 41))
        self.reset.setObjectName("reset")
        self.reset.clicked.connect(self.resetwindow)
        self.exit = QtWidgets.QPushButton(self.page)
        self.exit.setGeometry(QtCore.QRect(470, 460, 101, 41))
        self.exit.setObjectName("exit")
        self.exit.clicked.connect(MainWindow.close)
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic Tac Toe"))
        self.select_X.setText(_translate("MainWindow", "X"))
        self.select_O.setText(_translate("MainWindow", "O"))
        self.label.setText(_translate("MainWindow", "Choose your preferred option:"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
